# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20180426_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
