# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_auto_20180430_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='project_name',
            new_name='subject_name',
        ),
    ]
