# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0015_auto_20180927_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_code',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
