# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculus1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='stream_id',
        ),
        migrations.RemoveField(
            model_name='assignmenttopic',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='assignmenttopic',
            name='topic_id',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
