# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20180426_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='code',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=b'', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='enroll_key',
            field=models.CharField(max_length=20),
        ),
    ]
