# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0013_auto_20180927_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
