# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_assignmentdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='function_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='function_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Subject'),
        ),
    ]
