# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0017_auto_20181027_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
